# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZJH7EU9gCVJW11cd4yT4_aBTUlAf7k8
"""

from google.colab import files
files.upload()

import pandas as pd
import numpy as np

df = pd.read_csv("Glucose_Level_Estimation_AS726x.csv")

# Convert height (feet → meters)
df["HEIGHT_m"] = df["HEIGHT"] * 0.3048

# Compute BMI
df["BMI"] = df["WEIGHT"] / (df["HEIGHT_m"] ** 2)

df["GENDER"] = df["GENDER"].map({"M": 0, "F": 1})

df_final = df[["730nm", "AGE", "BMI", "GENDER", "GLUCOSE_LEVEL"]]

augmented_rows = []
AUGMENT_FACTOR = 5

for _, row in df_final.iterrows():
    for _ in range(AUGMENT_FACTOR):
        new_row = row.copy()

        # 730 nm optical noise (±2%)
        new_row["730nm"] *= np.random.uniform(0.98, 1.02)

        # BMI noise
        new_row["BMI"] += np.random.uniform(-0.3, 0.3)

        # Glucose tolerance noise
        new_row["GLUCOSE_LEVEL"] += np.random.uniform(-5, 5)

        augmented_rows.append(new_row)

aug_df = pd.DataFrame(augmented_rows)

# Combine real + synthetic
final_dataset = pd.concat([df_final, aug_df], ignore_index=True)
final_dataset = final_dataset.sample(frac=1).reset_index(drop=True)

final_dataset.to_csv("final_730nm_dataset.csv", index=False)

from google.colab import files
files.download("final_730nm_dataset.csv")

import pandas as pd

df = pd.read_csv("final_730nm_dataset.csv")

# Apply physiological bounds
df["GLUCOSE_LEVEL"] = df["GLUCOSE_LEVEL"].clip(lower=70, upper=250)
df["BMI"] = df["BMI"].clip(lower=18.5, upper=35)

# Save corrected dataset
df.to_csv("final_730nm_dataset_clipped.csv", index=False)

print(df.describe())

from google.colab import files
files.download("final_730nm_dataset.csv")

