# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZJH7EU9gCVJW11cd4yT4_aBTUlAf7k8
"""

from google.colab import files
files.upload()

import pandas as pd
import numpy as np

df = pd.read_csv("Glucose_Level_Estimation_AS726x.csv")

# Convert height (feet → meters)
df["HEIGHT_m"] = df["HEIGHT"] * 0.3048

# Compute BMI
df["BMI"] = df["WEIGHT"] / (df["HEIGHT_m"] ** 2)

df["GENDER"] = df["GENDER"].map({"M": 0, "F": 1})

df_final = df[["730nm", "AGE", "BMI", "GENDER", "GLUCOSE_LEVEL"]]

augmented_rows = []
AUGMENT_FACTOR = 5

for _, row in df_final.iterrows():
    for _ in range(AUGMENT_FACTOR):
        new_row = row.copy()

        # 730 nm optical noise (±2%)
        new_row["730nm"] *= np.random.uniform(0.98, 1.02)

        # BMI noise
        new_row["BMI"] += np.random.uniform(-0.3, 0.3)

        # Glucose tolerance noise
        new_row["GLUCOSE_LEVEL"] += np.random.uniform(-5, 5)

        augmented_rows.append(new_row)

aug_df = pd.DataFrame(augmented_rows)

# Combine real + synthetic
final_dataset = pd.concat([df_final, aug_df], ignore_index=True)
final_dataset = final_dataset.sample(frac=1).reset_index(drop=True)

final_dataset.to_csv("final_730nm_dataset.csv", index=False)

from google.colab import files
files.download("final_730nm_dataset.csv")

import pandas as pd

df = pd.read_csv("final_730nm_dataset.csv")

# Apply physiological bounds
df["GLUCOSE_LEVEL"] = df["GLUCOSE_LEVEL"].clip(lower=70, upper=250)
df["BMI"] = df["BMI"].clip(lower=18.5, upper=35)

# Save corrected dataset
df.to_csv("final_730nm_dataset_clipped.csv", index=False)

print(df.describe())

from google.colab import files
files.download("final_730nm_dataset.csv")

import pandas as pd
import numpy as np

df = pd.read_csv("final_730nm_dataset.csv")

print(df.isna().sum())
print(df.dtypes)

import pandas as pd
import numpy as np

df = pd.read_csv("final_730nm_dataset.csv")
print(df.shape)
df.head()

X = df[["730nm", "AGE", "BMI", "GENDER"]].values
y = df["GLUCOSE_LEVEL"].values
df["GENDER"].unique()
df["GENDER"] = df["GENDER"].replace({"M": 0, "F": 1})
df["GENDER"] = df["GENDER"].astype(float)

df[~np.isfinite(df["BMI"])]
df = df.replace([np.inf, -np.inf], np.nan)
df["BMI"] = df["BMI"].fillna(df["BMI"].median())

df[~np.isfinite(df["730nm"])]
df["730nm"] = df["730nm"].fillna(df["730nm"].median())

# Replace infinities with NaN
df = df.replace([np.inf, -np.inf], np.nan)

# Fill NaNs with median (safe for biomedical data)
df["730nm"] = df["730nm"].fillna(df["730nm"].median())
df["AGE"] = df["AGE"].fillna(df["AGE"].median())
df["BMI"] = df["BMI"].fillna(df["BMI"].median())
df["GENDER"] = df["GENDER"].fillna(df["GENDER"].mode()[0])

# Final check
print(df.isna().sum())

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# SAVE THESE VALUES (needed for watch)
means = scaler.mean_
scales = scaler.scale_

print("Means:", means)
print("Scales:", scales)

from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor

X = df[["730nm", "AGE", "BMI", "GENDER"]].values
y = df["GLUCOSE_LEVEL"].values

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

mlp = MLPRegressor(
    hidden_layer_sizes=(8,),
    activation="relu",
    solver="adam",
    max_iter=5000,
    early_stopping=True,
    validation_fraction=0.1,
    n_iter_no_change=20,
    random_state=42
)


mlp.fit(X_scaled, y)

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y, y_pred)
rmse = np.sqrt(mean_squared_error(y, y_pred))

print("MAE:", mae)
print("RMSE:", rmse)

W1 = mlp.coefs_[0]          # (4, 8)
b1 = mlp.intercepts_[0]    # (8,)
W2 = mlp.coefs_[1].flatten()  # (8,)
b2 = mlp.intercepts_[1][0]

print("W1:\n", W1)
print("b1:\n", b1)
print("W2:\n", W2)
print("b2:\n", b2)

means = scaler.mean_
scales = scaler.scale_

print("Means:", means)
print("Scales:", scales)

import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

X = df[["730nm", "AGE", "BMI", "GENDER"]].values
y = df["GLUCOSE_LEVEL"].values

# add quadratic term for 730nm
X_poly = np.column_stack([X[:,0], X[:,0]**2, X[:,1], X[:,2], X[:,3]])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_poly)

model = LinearRegression()
model.fit(X_scaled, y)

y_pred = model.predict(X_scaled)

mae = mean_absolute_error(y, y_pred)
rmse = np.sqrt(mean_squared_error(y, y_pred))

print("Polynomial Regression MAE:", mae)
print("Polynomial Regression RMSE:", rmse)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_poly, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LinearRegression()
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("Test MAE:", mae)
print("Test RMSE:", rmse)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_poly, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LinearRegression()
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("Test MAE:", mae)
print("Test RMSE:", rmse)

